theme: jekyll-theme-cayman
github:
  is_project_page: false
title: "PoseMaster Fusion: Transforming Images by Capturing Pose Dynamics"
description: |
Structured Pose Synthesis with Stable Diffusion to seamlessly modify your photos with any pose from doodles or references and enhance them using text prompts.
Aparna Shree Sivanandam, Poojitha Nandigam and Shubham Lohiya

